export const GET_BANNER_DATA_START = 'GET_BANNER_DATA_START';
export const GET_BANNER_DATA_SUCCESS = 'GET_BANNER_DATA_SUCCESS';
export const GET_BANNER_DATA_FAIL = 'GET_BANNER_DATA_FAIL';

export const GET_INTRODUCTION_DATA_START = 'GET_INTRODUCTION_DATA_START';
export const GET_INTRODUCTION_DATA_SUCCESS = 'GET_INTRODUCTION_DATA_SUCCESS';
export const GET_INTRODUCTION_DATA_FAIL = 'GET_INTRODUCTION_DATA_FAIL';

export const GET_ABOUT_DATA_START = 'GET_ABOUT_DATA_START';
export const GET_ABOUT_DATA_SUCCESS = 'GET_ABOUT_DATA_SUCCESS';
export const GET_ABOUT_DATA_FAIL = 'GET_ABOUT_DATA_FAIL';

export const GET_WHY_DATA_START = 'GET_WHY_DATA_START';
export const GET_WHY_DATA_SUCCESS = 'GET_WHY_DATA_SUCCESS';
export const GET_WHY_DATA_FAIL = 'GET_WHY_DATA_FAIL';

export const GET_WHY_SLIDER_DATA_START = 'GET_WHY_SLIDER_DATA_START';
export const GET_WHY_SLIDER_DATA_SUCCESS = 'GET_WHY_SLIDER_DATA_SUCCESS';
export const GET_WHY_SLIDER_DATA_FAIL = 'GET_WHY_SLIDER_DATA_FAIL';

export const GET_PRODUCTS_DATA_START = 'GET_PRODUCTS_DATA_START';
export const GET_PRODUCTS_DATA_SUCCESS = 'GET_PRODUCTS_DATA_SUCCESS';
export const GET_PRODUCTS_DATA_FAIL = 'GET_PRODUCTS_DATA_FAIL';

export const GET_PRODUCTS_IMGS_DATA_START = 'GET_PRODUCTS_IMGS_DATA_START';
export const GET_PRODUCTS_IMGS_DATA_SUCCESS = 'GET_PRODUCTS_IMGS_DATA_SUCCESS';
export const GET_PRODUCTS_IMGS_DATA_FAIL = 'GET_PRODUCTS_IMGS_DATA_FAIL';

export const GET_TESTIMONIALS_DATA_START = 'GET_TESTIMONIALS_DATA_START';
export const GET_TESTIMONIALS_DATA_SUCCESS = 'GET_TESTIMONIALS_DATA_SUCCESS';
export const GET_TESTIMONIALS_DATA_FAIL = 'GET_TESTIMONIALS_DATA_FAIL';

export const GET_CONTACT_DATA_START = 'GET_CONTACT_DATA_START';
export const GET_CONTACT_DATA_SUCCESS = 'GET_CONTACT_DATA_SUCCESS';
export const GET_CONTACT_DATA_FAIL = 'GET_CONTACT_DATA_FAIL';

export const GET_SOCIAL_CONTACT_DATA_START = 'GET_SOCIAL_CONTACT_DATA_START';
export const GET_SOCIAL_CONTACT_DATA_SUCCESS = 'GET_SOCIAL_CONTACT_DATA_SUCCESS';
export const GET_SOCIAL_CONTACT_DATA_FAIL = 'GET_SOCIAL_CONTACT_DATA_FAIL';

export const POST_CONTACT_DATA_START = 'POST_CONTACT_DATA_START';
export const POST_CONTACT_DATA_SUCCESS = 'POST_CONTACT_DATA_SUCCESS';
export const POST_CONTACT_DATA_FAIL = 'POST_CONTACT_DATA_FAIL';

export const POST_REVIEW_DATA_START = 'POST_REVIEW_DATA_START';
export const POST_REVIEW_DATA_SUCCESS = 'POST_REVIEW_DATA_SUCCESS';
export const POST_REVIEW_DATA_FAIL = 'POST_REVIEW_DATA_FAIL';

export const POST_ADDCART_DATA_START = 'POST_ADDCART_DATA_START';
export const POST_ADDCART_DATA_SUCCESS = 'POST_ADDCART_DATA_SUCCESS';
export const POST_ADDCART_DATA_FAIL = 'POST_ADDCART_DATA_FAIL';

export const GET_NUMCART_DATA_START = 'GET_NUMCART_DATA_START';
export const GET_NUMCART_DATA_SUCCESS = 'GET_NUMCART_DATA_SUCCESS';
export const GET_NUMCART_DATA_FAIL = 'GET_NUMCART_DATA_FAIL';

export const DELETE_CART_DATA_START = 'DELETE_CART_DATA_START';
export const DELETE_CART_DATA_SUCCESS = 'DELETE_CART_DATA_SUCCESS';
export const DELETE_CART_DATA_FAIL = 'DELETE_CART_DATA_FAIL';

export const POST_CHECKOUT_DATA_START = 'POST_CHECKOUT_DATA_START';
export const POST_CHECKOUT_DATA_SUCCESS = 'POST_CHECKOUT_DATA_SUCCESS';
export const POST_CHECKOUT_DATA_FAIL = 'POST_CHECKOUT_DATA_FAIL';